"use client";
import { useDashboard } from "./BusinessContext";

// Rendered inside a hidden `.print-only` block on every printable/exportable
// page — invisible on screen, shown only by print.css's `@media print` rule
// when the user picks Print or "Export to PDF" (both trigger window.print()).
export function PrintLetterhead({ reportTitle, dateRangeLabel, filtersLabel }: { reportTitle: string; dateRangeLabel?: string; filtersLabel?: string }) {
  const { business } = useDashboard();

  return (
    <div className="print-letterhead">
      <div className="flex items-center gap-3">
        <div className="print-logo">{business.name.charAt(0).toUpperCase()}</div>
        <div>
          <p style={{ fontWeight: 700, fontSize: 15 }}>{business.name}</p>
          {business.address && <p style={{ fontSize: 10, color: "#64748b" }}>{business.address}</p>}
          {business.phoneNumber && <p style={{ fontSize: 10, color: "#64748b" }}>{business.phoneNumber}</p>}
        </div>
      </div>
      <div style={{ textAlign: "right", fontSize: 11 }}>
        <p style={{ fontWeight: 700 }}>{reportTitle}</p>
        {dateRangeLabel && <p style={{ color: "#64748b" }}>{dateRangeLabel}</p>}
        {filtersLabel && <p style={{ color: "#64748b" }}>Filters: {filtersLabel}</p>}
        <p style={{ color: "#94a3b8", fontSize: 9 }}>Printed {new Date().toLocaleString("en-AU")}</p>
      </div>
    </div>
  );
}

export function PrintFooter() {
  const { business } = useDashboard();
  return (
    <div className="print-footer">
      <span>Generated by ZyncoAI — Confidential — {business.name}</span>
      <span className="print-page-count" />
    </div>
  );
}
