// Shared export engine used by every ExportMenu instance across the
// dashboard — one implementation of "styled Excel workbook" / "CSV" /
// "trigger browser print" rather than bespoke logic per page. See
// components/dashboard/ExportMenu.tsx for the UI half.
import * as XLSX from "xlsx-js-style";
import { toast } from "sonner";

export interface ExportColumn {
  key: string;
  label: string;
  width?: number; // characters, approximate
  format?: (value: any, row: Record<string, any>) => string;
  align?: "left" | "right" | "center";
  total?: "sum" | "count"; // include this column in the totals footer row
}

export interface ExportMeta {
  businessName: string;
  reportTitle: string;
  dateRangeLabel?: string;
  filtersLabel?: string;
}

export interface ExportSheet {
  name: string;
  columns: ExportColumn[];
  rows: Record<string, any>[];
  showTotals?: boolean;
}

const ACCENT_RGB = "2563EB";
const ALT_ROW_RGB = "F1F5F9";
const BORDER = { style: "thin", color: { rgb: "CBD5E1" } } as const;
const THIN_BORDERS = { top: BORDER, bottom: BORDER, left: BORDER, right: BORDER };

function cell(v: any, s?: any) {
  const t = v instanceof Date ? "s" : typeof v === "number" ? "n" : "s";
  return { v: v instanceof Date ? v.toLocaleString() : v ?? "", t, s };
}

function renderValue(col: ExportColumn, row: Record<string, any>): string | number {
  const raw = row[col.key];
  if (col.format) return col.format(raw, row);
  if (raw instanceof Date) return raw.toLocaleString();
  if (raw == null) return "";
  if (typeof raw === "boolean") return raw ? "Yes" : "No";
  return raw;
}

function buildSheet(sheet: ExportSheet, meta: ExportMeta): XLSX.WorkSheet {
  const aoa: any[][] = [];

  aoa.push([meta.businessName]);
  aoa.push([meta.reportTitle]);
  if (meta.dateRangeLabel) aoa.push([meta.dateRangeLabel]);
  if (meta.filtersLabel) aoa.push([`Filters: ${meta.filtersLabel}`]);
  aoa.push([]);

  const headerRowIdx = aoa.length;
  aoa.push(sheet.columns.map((c) => c.label));

  const dataStartIdx = aoa.length;
  for (const row of sheet.rows) {
    aoa.push(sheet.columns.map((c) => renderValue(c, row)));
  }

  let totalsRowIdx = -1;
  if (sheet.showTotals && sheet.columns.some((c) => c.total)) {
    totalsRowIdx = aoa.length;
    aoa.push(
      sheet.columns.map((c, i) => {
        if (i === 0) return "TOTAL";
        if (c.total === "count") return sheet.rows.length;
        if (c.total === "sum") return sheet.rows.reduce((s, r) => s + (Number(r[c.key]) || 0), 0);
        return "";
      })
    );
  }

  aoa.push([]);
  aoa.push([`Confidential — ${meta.businessName} — Generated by ZyncoAI on ${new Date().toLocaleString()}`]);

  const ws = XLSX.utils.aoa_to_sheet(aoa);

  // Title rows
  ws["A1"].s = { font: { bold: true, sz: 16, color: { rgb: ACCENT_RGB } } };
  ws["A2"].s = { font: { bold: true, sz: 12 } };
  for (let r = 2; r < headerRowIdx - 1; r++) {
    const ref = XLSX.utils.encode_cell({ r, c: 0 });
    if (ws[ref]) ws[ref].s = { font: { italic: true, sz: 9, color: { rgb: "64748B" } } };
  }

  // Header row — bold white on blue, bordered
  for (let c = 0; c < sheet.columns.length; c++) {
    const ref = XLSX.utils.encode_cell({ r: headerRowIdx, c });
    if (ws[ref]) {
      ws[ref].s = {
        font: { bold: true, color: { rgb: "FFFFFF" }, sz: 11 },
        fill: { patternType: "solid", fgColor: { rgb: ACCENT_RGB } },
        alignment: { horizontal: "center", vertical: "center" },
        border: THIN_BORDERS,
      };
    }
  }

  // Data rows — alternating fill + borders
  for (let r = 0; r < sheet.rows.length; r++) {
    const rowIdx = dataStartIdx + r;
    const isAlt = r % 2 === 1;
    for (let c = 0; c < sheet.columns.length; c++) {
      const ref = XLSX.utils.encode_cell({ r: rowIdx, c });
      if (!ws[ref]) continue;
      ws[ref].s = {
        font: { sz: 10 },
        fill: isAlt ? { patternType: "solid", fgColor: { rgb: ALT_ROW_RGB } } : undefined,
        alignment: { horizontal: sheet.columns[c].align || "left", vertical: "center" },
        border: THIN_BORDERS,
      };
    }
  }

  // Totals row — bold, top border
  if (totalsRowIdx > -1) {
    for (let c = 0; c < sheet.columns.length; c++) {
      const ref = XLSX.utils.encode_cell({ r: totalsRowIdx, c });
      if (!ws[ref]) continue;
      ws[ref].s = {
        font: { bold: true, sz: 10 },
        border: { top: { style: "medium", color: { rgb: "0F172A" } }, bottom: THIN_BORDERS.bottom },
        alignment: { horizontal: sheet.columns[c].align || "left" },
      };
    }
  }

  // Footer watermark
  const footerRowIdx = aoa.length - 1;
  const footerRef = XLSX.utils.encode_cell({ r: footerRowIdx, c: 0 });
  if (ws[footerRef]) ws[footerRef].s = { font: { italic: true, sz: 8, color: { rgb: "94A3B8" } } };

  // Column widths — approximate from label + content length
  ws["!cols"] = sheet.columns.map((c, i) => {
    const maxContentLen = sheet.rows.reduce((max, row) => Math.max(max, String(renderValue(c, row)).length), c.label.length);
    return { wch: c.width || Math.min(50, Math.max(10, maxContentLen + 2)) };
  });

  // Merge title rows across all columns so they read as a banner
  ws["!merges"] = [
    { s: { r: 0, c: 0 }, e: { r: 0, c: Math.max(0, sheet.columns.length - 1) } },
    { s: { r: 1, c: 0 }, e: { r: 1, c: Math.max(0, sheet.columns.length - 1) } },
  ];

  return ws;
}

export function exportToExcel(sheets: ExportSheet[], meta: ExportMeta, filename: string) {
  const wb = XLSX.utils.book_new();
  for (const sheet of sheets) {
    XLSX.utils.book_append_sheet(wb, buildSheet(sheet, meta), sheet.name.slice(0, 31));
  }
  XLSX.writeFile(wb, filename.endsWith(".xlsx") ? filename : `${filename}.xlsx`);
}

export function exportToCsv(columns: ExportColumn[], rows: Record<string, any>[], filename: string) {
  const escape = (v: any) => {
    const s = String(v ?? "");
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  };
  const lines = [
    columns.map((c) => escape(c.label)).join(","),
    ...rows.map((row) => columns.map((c) => escape(renderValue(c, row))).join(",")),
  ];
  const blob = new Blob([lines.join("\n")], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".csv") ? filename : `${filename}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

export function triggerPrint(kind: "print" | "pdf") {
  if (kind === "pdf") {
    toast.info('In the print dialog, choose "Save as PDF" as the destination.');
  }
  // Small delay lets the toast paint before the (blocking) print dialog opens.
  setTimeout(() => window.print(), 150);
}

export async function logExport(section: string, format: "excel" | "csv" | "pdf" | "print", recordCount: number) {
  try {
    await fetch("/api/business/export/log", {
      method: "POST",
      headers: { "content-type": "application/json" },
      credentials: "include",
      body: JSON.stringify({ section, format, recordCount }),
    });
  } catch {
    // best-effort audit trail — never block the user's export on this
  }
}

const CONSENT_KEY = "zyn_export_consent_ack";

export function hasAckedExportConsent(): boolean {
  if (typeof window === "undefined") return true;
  return localStorage.getItem(CONSENT_KEY) === "1";
}

export function ackExportConsent() {
  if (typeof window !== "undefined") localStorage.setItem(CONSENT_KEY, "1");
}

export function slugFilename(businessName: string, section: string) {
  const clean = businessName.replace(/[^a-zA-Z0-9]/g, "");
  const date = new Date().toLocaleDateString("en-AU", { day: "2-digit", month: "short", year: "numeric" }).replace(/\s/g, "");
  return `${clean}-${section}-${date}`;
}

export interface ScheduleProvider {
  id: string;
  name: string;
  title?: string | null;
  appointments: { startAt: string; endAt: string; recordType: string | null; contactName: string | null }[];
}

const SCHEDULE_START_HOUR = 7;
const SCHEDULE_END_HOUR = 19;
const SCHEDULE_SLOT_MIN = 30;

export function buildScheduleSlots(): string[] {
  const slots: string[] = [];
  for (let h = SCHEDULE_START_HOUR; h < SCHEDULE_END_HOUR; h++) {
    for (let m = 0; m < 60; m += SCHEDULE_SLOT_MIN) slots.push(`${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}`);
  }
  return slots;
}

export function buildScheduleGrid(provider: ScheduleProvider, weekDays: Date[]): string[][] {
  const slots = buildScheduleSlots();
  const grid: string[][] = slots.map(() => Array(weekDays.length).fill(""));
  for (const appt of provider.appointments) {
    const start = new Date(appt.startAt);
    const dayIdx = weekDays.findIndex((d) => d.toDateString() === start.toDateString());
    if (dayIdx === -1) continue;
    const slotIdx = Math.round((start.getHours() * 60 + start.getMinutes() - SCHEDULE_START_HOUR * 60) / SCHEDULE_SLOT_MIN);
    if (slotIdx >= 0 && slotIdx < slots.length) {
      grid[slotIdx][dayIdx] = `${appt.contactName || "Booked"} (${appt.recordType || "Appt"})`;
    }
  }
  return grid;
}

// A weekly calendar grid (times down the left, days across the top) — one
// sheet per provider, since Admin can export every provider's schedule at
// once while a Doctor only ever has their own. Distinct from exportToExcel
// (columnar list) because a schedule genuinely reads better as a grid.
export function exportScheduleToExcel(providers: ScheduleProvider[], weekStart: Date, meta: ExportMeta, filename: string) {
  const wb = XLSX.utils.book_new();
  const weekDays = Array.from({ length: 7 }).map((_, i) => new Date(weekStart.getTime() + i * 86400000));
  const dayLabels = weekDays.map((d) => d.toLocaleDateString("en-AU", { weekday: "short", day: "2-digit", month: "short" }));
  const slots = buildScheduleSlots();

  for (const provider of providers) {
    const grid = buildScheduleGrid(provider, weekDays);
    const aoa: any[][] = [
      [meta.businessName],
      [`${provider.name}${provider.title ? ` — ${provider.title}` : ""} — Weekly Schedule`],
      [`Week of ${weekDays[0].toLocaleDateString("en-AU")}`],
      [],
      ["Time", ...dayLabels],
      ...slots.map((slot, i) => [slot, ...grid[i]]),
      [],
      [`Confidential — ${meta.businessName} — Generated by ZyncoAI on ${new Date().toLocaleString()}`],
    ];

    const ws = XLSX.utils.aoa_to_sheet(aoa);
    ws["!merges"] = [
      { s: { r: 0, c: 0 }, e: { r: 0, c: 7 } },
      { s: { r: 1, c: 0 }, e: { r: 1, c: 7 } },
    ];
    if (ws["A1"]) ws["A1"].s = { font: { bold: true, sz: 16, color: { rgb: ACCENT_RGB } } };
    if (ws["A2"]) ws["A2"].s = { font: { bold: true, sz: 12 } };

    for (let c = 0; c < 8; c++) {
      const ref = XLSX.utils.encode_cell({ r: 4, c });
      if (ws[ref]) {
        ws[ref].s = {
          font: { bold: true, color: { rgb: "FFFFFF" }, sz: 10 },
          fill: { patternType: "solid", fgColor: { rgb: ACCENT_RGB } },
          alignment: { horizontal: "center" },
          border: THIN_BORDERS,
        };
      }
    }

    for (let r = 0; r < slots.length; r++) {
      const rowIdx = 5 + r;
      const timeRef = XLSX.utils.encode_cell({ r: rowIdx, c: 0 });
      if (ws[timeRef]) ws[timeRef].s = { font: { bold: true, sz: 9 }, fill: { patternType: "solid", fgColor: { rgb: ALT_ROW_RGB } }, border: THIN_BORDERS };
      for (let c = 1; c < 8; c++) {
        const ref = XLSX.utils.encode_cell({ r: rowIdx, c });
        if (ws[ref]) ws[ref].s = { font: { sz: 9 }, border: THIN_BORDERS, alignment: { wrapText: true, vertical: "center" } };
      }
    }

    ws["!cols"] = [{ wch: 8 }, ...Array(7).fill({ wch: 22 })];
    XLSX.utils.book_append_sheet(wb, ws, (provider.name || "Schedule").slice(0, 31));
  }

  XLSX.writeFile(wb, filename.endsWith(".xlsx") ? filename : `${filename}.xlsx`);
}
